language: php

php:
  - 7.0

matrix:
  fast_finish: true

cache:
  directories:
    - $HOME/.composer
    - build/cache

install:
  - composer install --prefer-dist

script:
  - vendor/bin/atoum -d Test/
