language: php

php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4

matrix:
  fast_finish: true

cache:
  directories:
    - $HOME/.composer
    - build/cache

install:
  - composer install --prefer-dist

script:
  - vendor/bin/atoum -d Test/
